#!/bin/bash

# Script to sync wallpaper between swww/hyprlock and SDDM
# This script needs to be run with sudo for copying to system directories

WALLPAPER_CACHE_DIR="$HOME/.config/hypr/cache"
WALLPAPER_FILE="$WALLPAPER_CACHE_DIR/current_wallpaper"
SDDM_THEME_DIR="/usr/share/sddm/themes/silent"
SDDM_CONFIG="/usr/share/sddm/themes/silent/theme.conf"

# Function to get current wallpaper from cache file
get_current_wallpaper() {
    # When running with sudo, use the original user's home directory
    if [ -n "$SUDO_USER" ]; then
        local user_home=$(getent passwd "$SUDO_USER" | cut -d: -f6)
        local user_cache_file="$user_home/.config/hypr/cache/current_wallpaper"
        if [ -f "$user_cache_file" ]; then
            cat "$user_cache_file"
            return
        fi
    fi
    
    # Fallback: use local cache file or swww
    if [ -f "$WALLPAPER_FILE" ]; then
        cat "$WALLPAPER_FILE"
    else
        # Try to get from swww as current user
        swww query 2>/dev/null | grep "image:" | sed 's/.*image: //' | xargs
    fi
}

# Function to copy wallpaper to SDDM theme directory
copy_wallpaper_to_sddm() {
    local wallpaper_path="$1"
    
    if [ -z "$wallpaper_path" ] || [ ! -f "$wallpaper_path" ]; then
        echo "Error: Invalid wallpaper path: $wallpaper_path"
        return 1
    fi
    
    # Get wallpaper filename
    local wallpaper_name=$(basename "$wallpaper_path")
    local sddm_wallpaper_path="$SDDM_THEME_DIR/backgrounds/$wallpaper_name"
    
    echo "Copying wallpaper to SDDM: $wallpaper_path -> $sddm_wallpaper_path"
    
    # Copy wallpaper to SDDM backgrounds directory
    cp "$wallpaper_path" "$sddm_wallpaper_path"
    if [ $? -eq 0 ]; then
        echo "Wallpaper copied successfully"
        echo "$wallpaper_name" > "$WALLPAPER_CACHE_DIR/sddm_wallpaper_name"
        return 0
    else
        echo "Error: Failed to copy wallpaper"
        return 1
    fi
}

# Function to update SDDM configuration
update_sddm_config() {
    local wallpaper_name="$1"
    
    if [ -z "$wallpaper_name" ]; then
        wallpaper_name="default.jpg"
    fi
    
    echo "Updating SDDM configuration to use: $wallpaper_name"
    
    # Create or update SDDM theme.conf
    cat > "$SDDM_CONFIG" << EOF
; Custom SDDM configuration to match desktop wallpaper
; Auto-generated by wallpaper sync script

[General]
scale = 1.0
enable-animations = true
animated-background-placeholder = ""
background-fill-mode = "fill"

[LockScreen]
display = true
padding-top = 0
padding-right = 0
padding-bottom = 0
padding-left = 0
background = "$wallpaper_name"
use-background-color = false
background-color = "#000000"
blur = 32
brightness = 0.0
saturation = 0.0

[LockScreen.Clock]
display = true
position = "top-center"
align = "center"
format = "hh:mm"
font-family = "RedHatDisplay"
font-size = 70
font-weight = 900
color = "#FFFFFF"

[LockScreen.Date]
display = true
format = "dddd, MMMM dd, yyyy"
locale = "en_US"
font-family = "RedHatDisplay"
font-size = 14
font-weight = 600
color = "#FFFFFF"
margin-top = -15

[LockScreen.Message]
display = true
position = "bottom"-center
align = "center"
text = "Press any key"
font-family = "RedHatDisplay"
font-size = 12
font-weight = 400
display-icon = true
icon = "enter.svg"
icon-size = 16
color = "#FFFFFF"
paint-icon = true
spacing = 0

[LoginScreen]
background = "$wallpaper_name"
use-background-color = false
background-color = "#000000"
blur = 0
brightness = 0.0
saturation = 0.0

[LoginScreen.LoginArea]
position = "center"
margin = -1

[LoginScreen.LoginArea.Avatar]
shape = "circle"
border-radius = 35
active-size = 120
inactive-size = 80
inactive-opacity = 0.35
active-border-size = 0
inactive-border-size = 0
active-border-color = "#FFFFFF"
inactive-border-color = "#FFFFFF"

[LoginScreen.LoginArea.Username]
font-family = "RedHatDisplay"
font-size = 16
font-weight = 700
color = "#FFFFFF"
margin = 10

[LoginScreen.LoginArea.PasswordInput]
width = 200
height = 30
display-icon = true
font-family = "RedHatDisplay"
font-size = 12
icon = "password.svg"
icon-size = 16
content-color = "#FFFFFF"
background-color = "#FFFFFF"
background-opacity = 0.15
border-size = 0
border-color = "#FFFFFF"
border-radius-left = 10
border-radius-right = 10
margin-top = 10
masked-character = "●"

[LoginScreen.LoginArea.LoginButton]
background-color = "#FFFFFF"
background-opacity = 0.15
active-background-color = "#FFFFFF"
active-background-opacity = 0.30
icon = "arrow-right.svg"
icon-size = 18
content-color = "#FFFFFF"
active-content-color = "#FFFFFF"
border-size = 0
border-color = "#FFFFFF"
border-radius-left = 10
border-radius-right = 10
margin-left = 5
show-text-if-no-password = true
hide-if-not-needed = false
font-family = "RedHatDisplay"
font-size = 12
font-weight = 600

[LoginScreen.LoginArea.Spinner]
display-text = true
text = "Logging in"
font-family = "RedHatDisplay"
font-weight = 600
font-size = 14
icon-size = 30
icon = "spinner.svg"
color = "#FFFFFF"
spacing = 5

[LoginScreen.LoginArea.WarningMessage]
font-family = "RedHatDisplay"
font-size = 11
font-weight = 400
normal-color = "#FFFFFF"
warning-color = "#FFFFFF"
error-color = "#FFFFFF"
margin-top = 10

[LoginScreen.MenuArea.Buttons]
margin-top = 50
margin-right = 50
margin-bottom = 50
margin-left = 50
size = 30
border-radius = 5
spacing = 10
font-family = "RedHatDisplay"

[LoginScreen.MenuArea.Popups]
max-height = 300
item-height = 30
item-spacing = 2
padding = 5
display-scrollbar = true
margin = 5
background-color = "#FFFFFF"
background-opacity = 0.15
active-option-background-color = "#FFFFFF"
active-option-background-opacity = 0.30
content-color = "#FFFFFF"
active-content-color = "#FFFFFF"
font-family = "RedHatDisplay"
border-size = 0
border-color = "#FFFFFF"
font-size = 11
icon-size = 16

[LoginScreen.MenuArea.Session]
display = true
position = "bottom-left"
index = 0
popup-direction = "up"
popup-align = "center"
display-session-name = true
button-width = 200
popup-width = 200
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 0.30
content-color = "#FFFFFF"
active-content-color = "#FFFFFF"
border-size = 0
font-size = 10
icon-size = 16

[LoginScreen.MenuArea.Layout]
display = true
position = "bottom-right"
index = 0
popup-direction = "up"
popup-align = "center"
popup-width = 180
display-layout-name = true
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 0.30
content-color = "#FFFFFF"
active-content-color = "#FFFFFF"
border-size = 0
font-size = 10
icon = "language.svg"
icon-size = 16

[LoginScreen.MenuArea.Keyboard]
display = true
position = "bottom-right"
index = 0
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 0.30
content-color = "#FFFFFF"
active-content-color = "#FFFFFF"
border-size = 0
icon = "keyboard.svg"
icon-size = 16

[LoginScreen.MenuArea.Power]
display = true
position = "bottom-right"
index = 0
popup-direction = "up"
popup-align = "center"
popup-width = 100
background-color = "#FFFFFF"
background-opacity = 0.0
active-background-opacity = 0.30
content-color = "#FFFFFF"
active-content-color = "#FFFFFF"
border-size = 0
icon = "power.svg"
icon-size = 16

[LoginScreen.VirtualKeyboard]
scale = 1.0
position = "login"
start-hidden = true
background-color = "#FFFFFF"
background-opacity = 0.15
key-content-color = "#FFFFFF"
key-color = "#FFFFFF"
key-opacity = 0.15
key-active-background-color = "#FFFFFF"
key-active-opacity = 0.30
selection-background-color = "#CCCCCC"
selection-content-color = "#FFFFFF"
primary-color = "#FFF"
border-size = 0
border-color = "#000000"

[Tooltips]
enable = true
font-family = "RedHatDisplay"
font-size = 11
content-color = "#FFFFFF"
background-color = "#FFFFFF"
background-opacity = 0.15
border-radius = 5
disable-user = false
disable-login-button = false
EOF

    echo "SDDM configuration updated successfully"
}

# Function to sync current wallpaper to SDDM
sync_wallpaper() {
    echo "Syncing wallpaper to SDDM..."
    
    # Get current wallpaper
    local current_wallpaper=$(get_current_wallpaper)
    
    if [ -z "$current_wallpaper" ]; then
        echo "Error: No current wallpaper found"
        return 1
    fi
    
    echo "Current wallpaper: $current_wallpaper"
    
    # Copy wallpaper to SDDM
    if copy_wallpaper_to_sddm "$current_wallpaper"; then
        local wallpaper_name=$(basename "$current_wallpaper")
        update_sddm_config "$wallpaper_name"
        echo "Wallpaper sync completed successfully"
        return 0
    else
        echo "Error: Failed to sync wallpaper"
        return 1
    fi
}

# Function to monitor wallpaper changes
monitor_wallpaper_changes() {
    echo "Monitoring wallpaper changes for SDDM sync..."
    
    # Create cache directory
    mkdir -p "$WALLPAPER_CACHE_DIR"
    
    # Initial sync
    sync_wallpaper
    
    # Monitor for changes
    while true; do
        current=$(get_current_wallpaper)
        stored=""
        if [ -f "$WALLPAPER_FILE" ]; then
            stored=$(cat "$WALLPAPER_FILE")
        fi
        
        if [ "$current" != "$stored" ]; then
            echo "Wallpaper changed, syncing to SDDM..."
            sync_wallpaper
        fi
        
        sleep 2
    done
}

# Main execution
case "${1:-sync}" in
    "sync")
        sync_wallpaper
        ;;
    "monitor")
        monitor_wallpaper_changes
        ;;
    *)
        echo "Usage: $0 [sync|monitor]"
        echo "  sync    - Sync current wallpaper to SDDM (default)"
        echo "  monitor - Monitor and auto-sync wallpaper changes"
        exit 1
        ;;
esac