# Background and foreground colors
background = #0D151D
foreground = #dbdbdb

# Standard colors
palette = 0=#0D151D
palette = 1=#7BABC5
palette = 2=#A3D7E4
palette = 3=#95C8D4
palette = 4=#93b1c2
palette = 5=#a2b7c3
palette = 6=#84AEBA
palette = 7=#C0F6F9

# Bright colors
palette = 8=#71889e
palette = 9=#b9d4e3
palette = 10=#e9f6fa
palette = 11=#d5ebf0
palette = 12=#cddce4
palette = 13=#d9e2e8
palette = 14=#bdd6dc
palette = 15=#dbdbdb
