background            #0D151D
foreground            #dbdbdb

# black
color0  #0D151D
color8  #71889e

# red
color1  #7BABC5
color9  #b9d4e3

# green
color2  #A3D7E4
color10 #e9f6fa

# yellow
color3  #95C8D4
color11 #d5ebf0

# blue
color4  #93b1c2
color12 #cddce4

# magenta
color5  #a2b7c3
color13 #d9e2e8

#cyan
color6  #84AEBA
color14 #bdd6dc

#white
color7  #C0F6F9
color15 #dbdbdb


