name: Aether
accent: "#93b1c2"
cursor: "#93b1c2"
background: "#0D151D"
foreground: "#dbdbdb"
details: darker

terminal_colors:
  normal:
    black:   "#0D151D"
    red:     "#7BABC5"
    green:   "#A3D7E4"
    yellow:  "#95C8D4"
    blue:    "#93b1c2"
    magenta: "#a2b7c3"
    cyan:    "#84AEBA"
    white:   "#C0F6F9"
  bright:
    black:   "#71889e"
    red:     "#b9d4e3"
    green:   "#e9f6fa"
    yellow:  "#d5ebf0"
    blue:    "#cddce4"
    magenta: "#d9e2e8"
    cyan:    "#bdd6dc"
    white:   "#dbdbdb"
