# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = swww-daemon
exec-once = sleep 0.5 && ( [ -f ~/.config/hypr/cache/current_wallpaper ] && swww img ~/.config/hypr/cache/current_wallpaper || swww img ~/.config/aether/theme/backgrounds/wallhaven-qdody5.jpg )
exec-once = elephant
exec-once = waybar
exec-once = ~/.config/hypr/scripts/swww-wallpaper-monitor.sh &
exec-once = sudo -n ~/.arch/dotfiles/hypr/scripts/sync-sddm-wallpaper.sh sync >/dev/null 2>&1 &
exec-once = ~/.local/bin/aether-watcher start
# exec-once = cliphist server
