# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hyprland/monitors.conf
source = ~/.config/hyprland/input.conf
source = ~/.config/hyprland/bindings.conf
source = ~/.config/hyprland/envs.conf
source = ~/.config/hyprland/looknfeel.conf
source = ~/.config/hyprland/autostart.conf
source = ~/.config/hyprland/windowrules.conf

# Enhanced Web Apps Window Rules
source = ~/.config/hyprland/webapps-enhanced-clean.conf

# End Enhanced Web Apps
