source = ~/.config/aether//theme/hyprlock.conf

background {
    monitor =
    color = $color
    path = /home/nik/.config/aether/theme/backgrounds/wallhaven-qdody5.jpg
    blur_passes = 3
}

general {
    no_fade_in = false
    no_fade_out = false
}

animations {
    enabled = true
    bezier = verySlow, 0.05, 0.01, 0.05, 1
    animation = fadeIn, 1, 10, verySlow
    animation = fadeOut, 1, 10, verySlow
    animation = inputFieldDots, 1, 4, verySlow
}

input-field {
    monitor =
    size = 150, 25
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 1

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color
    font_size = 12

    placeholder_text =   Password 󰈷 
    check_color = $check_color
    fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>

    rounding = 20
    shadow_passes = 0
    fade_on_empty = true
}

label {
    text = cmd[update:1000] date +%H%M
    color = $font_color
    font_size = 40
    font_family = MoonGloss Display Thick
    position = 0, 200
    halign = center
    valign = center
}

label {
    text = cmd[update:900000] ~/.config/hypr/scripts/weather-hyprlock.sh
    color = $font_color
    font_size = 12
    font_family = MoonGloss Display Thin
    position = 0, 100
    halign = center
    valign = center
}

label {
    text = cmd[update:30000] ~/.config/hypr/battery-hyprlock.sh
    color = $font_color
    font_size = 10
    font_family = MoonGloss Display Thin
    position = 0, 50
    halign = center
    valign = bottom
}

auth {
    fingerprint:enabled = true
}
