# Change the look'n'feel
source = ~/.config/aether/theme/hyprland.conf
# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 3
    gaps_out = 3
    border_size = 1             # Thickness in pixels
    col.active_border = $activeBorderColor rgba(00000000) 45deg
    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 15
    active_opacity = 0.8
    inactive_opacity = 0.5
    blur {
        enabled = true       # (bool) Enable the blur effect
        size = 8             # (int) Blur size (distance/intensity). Min 1.
        passes = 2           # (int) The number of passes to perform (higher = smoother, but slower). Min 1.
        ignore_opacity = true # (bool) Make the blur layer ignore the window's opacity.
        new_optimizations = true # (bool) Highly recommended for performance.
        noise = 0.0117       # (float) Add noise to the blur effect (0.0 - 1.0)
        contrast = 0.8916    # (float) Adjust contrast of the blur (0.0 - 2.0)
        brightness = 1.0     # (float) Adjust brightness of the blur (0.0 - 2.0)
        vibrancy = 0.1696   # (float) Add vibrancy to colors (0.0 - 1.0)
    }
    shadow {
        enabled = true       # (bool) Enable drop shadows
        range = 10            # (int) Shadow range ("size") in pixels.
        render_power = 4     # (int) Falloff power (higher = faster falloff, sharper shadow). [1 - 4]
        color = 0xee1a1a1a   # (color) Shadow's color (RGBA format, 'ee' is the alpha/opacity).
        # You can also tune: offset (vec2) and scale (float).
    }
}

# Layer rules for transparency effects
# layerrule = blur 1, address:0x[waybar]

